### ISSUE TITLE
null FKs return non-null objects with all-null attributes

### ISSUE THREAD

**Issue by neopunisher** [coleifer/peewee#1012]
when doing a left join across a nullable FK, peewee 2.8.1 populates an empty object where the null is, rather than putting a `None` in the attribute.  example:

```python
import logging, os, sys
import peewee as pw

logger = logging.getLogger('peewee')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())

db_fn = 'example.db'
if os.path.exists(db_fn): os.remove(db_fn)
db = pw.SqliteDatabase(db_fn)

class Person(pw.Model):
  name = pw.CharField()
  class Meta:
    database = db

class Pet(pw.Model):
  name = pw.CharField()
  owner = pw.ForeignKeyField(db_column='owner_id', rel_model=Person, to_field='id', null=True)
  class Meta:
    database = db

db.connect()
db.create_tables([Person, Pet])

Pet.create(name='Chance', owner=None)

chance = Pet.select(Pet, Person).join(Person, join_type=pw.JOIN.LEFT_OUTER, on=Pet.owner).get()
print 'chance', chance
print 'chance.owner_id', chance.owner_id
print 'chance.owner', chance.owner
print 'chance.owner.id', chance.owner.id
```

output:

```sql
$ python test_join_null_fk.py 
('CREATE TABLE "person" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL)', [])
('CREATE TABLE "pet" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "owner_id" INTEGER, FOREIGN KEY ("owner_id") REFERENCES "person" ("id"))', [])
('CREATE INDEX "pet_owner_id" ON "pet" ("owner_id")', [])
('INSERT INTO "pet" ("name", "owner_id") VALUES (?, ?)', [u'Chance', None])
('SELECT "t1"."id", "t1"."name", "t1"."owner_id", "t2"."id", "t2"."name" FROM "pet" AS t1 LEFT OUTER JOIN "person" AS t2 ON ("t1"."owner_id" = "t2"."id") LIMIT 1 OFFSET 0', [])
chance <__main__.Pet object at 0x7f9b3c249950>
chance.owner_id None
chance.owner <__main__.Person object at 0x7f9b3c249b90>
chance.owner.id None
```

is this the intended behavior?  consensus here is this is a bug and that:

1. `chance.owner` should be `None`, not an empty `Person` object with all null attributes
2. `chance.owner.id` should throw `AttributeError: 'NoneType' object has no attribute 'id'`

we couldn't find any documentation about what this should do one way or the other, nor any old issues that address this.

**Comment by coleifer** [comment]
I agree this has the potential to be very confusing. Ideally Peewee would see that the foreign key from Pet -> Person is NULL and would not assign a related object. The problem arises, though, if the query looks like this:

```python
chance = (Pet
          .select(Pet.name, Person.name)
          .join(Person, JOIN.LEFT_OUTER)
          .get())
```

Since the foreign key column was not explicitly selected, Peewee doesn't actually know whether or not "chance" has an owner. It could be inferred that, since name is not null, and the name returned by the db *is* null, that there is no owner...but prefer to avoid this type of heuristic.

Alternatively, Peewee could skip on creating the related object when all of the column values were NULL. This gets into a different problem, though. Consider if Person has two new fields, a nullable column and a foreign key to a third model, Address:

```python
chance = (Pet
          .select(Pet.name, Person.some_nullable_column, Address.city)
          .join(Person, JOIN.LEFT_OUTER)
          .join(Address)
          .get())
```

In the above case, say "some_nullable_column" is NULL for chance's owner, but the address has a valid city. If we dropped the Person record because all columns were null, presumably there'd be no way to get to the city (pet.person.address.city would fail because pet.person is None).

This would require the introduction of another check, which would be "If all columns are null, and all columns on any dependent models are also null". 

A final consideration is that this has been the behavior of Peewee for a while, presumably since I introduced the ModelQueryResultWrapper... Be concerned about breakage.

------------------------------

So, while it's not the most desirable thing in the world to have this empty model, the alternatives don't seem to me to be perfect either.

**Comment by neopunisher** [comment]
A final consideration is that this has been the behavior of Peewee for a while, presumably since I introduced the ModelQueryResultWrapper... Be concerned about breakage.

i'd argue that's a reason not to do it as a 2.8.2 release, but as 2.9 or 3.0, that's where minor behavior changes are to be expected.  possibly expose a setting for backward compatibility if really concerned. We could add a setting for it and disable it by default. Then code going forward wont rely on this weird behavior. I don't know of any other ORM that returns empty models super weird 

> It could be inferred that, since name is not null, and the name returned by the db is null, that there is no owner...but prefer to avoid this type of heuristic.

agree that would be a bad heuristic.  but if a PK column (or any not-null column) ​*is*​ selected, you don't need a heuristic, as you know conclusively that there is no matching record.  

> presumably there'd be no way to get to the city (pet.person.address.city would fail because pet.person is None).

yeah, but how often as people doing Cartesian joins across null relations?  that seems a very esoteric example to be optimizing the API for. What is the Address tied to? If the address belongs to the person then i would expect address and person to be None

at min. i think this is good fodder for documenting the behavior.  would you be open to a doc PR for that?

**Comment by coleifer** [comment]
> I don't know of any other ORM that returns empty models super weird 

Thanks for editorializing. I don't know who you are, but the fact that you find this super weird really adds a lot to the conversation. Blocking you from further posts.

> yeah, but how often as people doing Cartesian joins across null relations? that seems a very esoteric example to be optimizing the API for.

Say there is a website where users can post messages. A message has an optional foreign key to a logged-in user, and the user has a nullable "display name". The User also has a foreign key to some profile data with an avatar. In that case you would be selecting Message, User.display_name (nullable), ProfileData.avatar, and the situation would be the same. I agree it's a stretch but just because you are having trouble imagining it doesn't mean somebody won't file a bug report down the road for exactly that situation.

> at min. i think this is good fodder for documenting the behavior. would you be open to a doc PR for that?

I agree that it does need to be explained, but I can handle the docs. After all the stuff with your buddy I'm not too excited about more PRs from your team.

I'd rather hit on an actual solution to this issue, but as I pointed out, it's not as simple as it seems.

*If* the user selects the foreign key field and it is null, then it's a safe bet to skip object creation. Same, as you mentioned, if they select the related object's primary key. Beyond that it gets murky. I'll look into implementing this.

**Comment by coleifer** [comment]
I like how you edited your comment to put "super weird" in bold tags.

Also, cool emojis bro.

![no-need-upset](https://cloud.githubusercontent.com/assets/119974/16817703/a5b42b36-4909-11e6-9e4f-3725095a3448.gif)

**Comment by tbranyen** [comment]
Blocking someone for that is *super weird* **bro**

**Comment by coleifer** [comment]
@tbranyen, this guy's manager caused quite a lot of drama on here a few weeks ago. I'm just trying to nip it in the bud.

**Comment by eberkund** [comment]
You take offence far too easily

**Comment by coleifer** [comment]
Sure bro. You read the stuff dude posted on here a few weeks ago?

**Comment by lgdexter** [comment]
OP aside, I would at least consider setting null references to `None` instead of an empty model.

**Comment by coleifer** [comment]
@lgdexter, have you read my responses? I definitely plan to fix this.

**Comment by coleifer** [comment]
Here's the plan for the fix:

> If the user selects the foreign key field and it is null, then it's a safe bet to skip object creation. Same, as you mentioned, if they select the related object's primary key. Beyond that it gets murky. I'll look into implementing this.

**Comment by randalljason** [comment]
If you now agree with OP, are you going to leave him banned?

**Comment by coleifer** [comment]
I agreed with him from the start?

**Comment by randalljason** [comment]
Then why ban him?  That's definitely **WEIRD**.

**Comment by randalljason** [comment]
> Sure bro. You read the stuff dude posted on here a few weeks ago?

What stuff?  https://www.google.com/search?q=neopunisher+peewee+site%3Agithub.com  You're a liar.

**Comment by coleifer** [comment]
Not him, his buddy keredson.

**Comment by coleifer** [comment]
Why would I make this up?

**Comment by coleifer** [comment]
@randalljason -- to make a long story short, this guy (not neopunisher, but his coworker and team lead or something) started posting issues... He would get very upset if I disagreed with his ideas. He did some things that really upset me. I won't go into all of it here, but suffice to say it was a lot of stuff, and not limited to just GitHub. He accused me of lying despite the documentation *and* git commit history showing the opposite, among other things.

What does this have to do with neopunisher?

Well, when the trouble-maker was busy causing trouble over here, neopunisher would do small stuff like posting thumbs-up emojis on his teammates posts and thumbs-down on mine. Silly stuff.

Today when he posted an issue, I took the time to provide what I thought was a very thorough and clear description of the issue as I saw it. But by his comments, I felt concerned that he would cause problems like his teammate had, so I decided to nip it in the bud, before it could be a larger issue.

Believe me, I don't take blocking a user lightly, and the only two users I've ever blocked are those two.

**Comment by randalljason** [comment]
You banned him (an action you don't take lightly) because you don't like his buddy, and he previously thumbs-down your comment.  Got it!

**Comment by coleifer** [comment]
@randalljason -- yes, I was being bullied by a user a few weeks ago, and it was pretty awful actually. And this feels very similar. I took action to prevent the bully's friend and colleague from being able to do further damage, and a very similar thing happened. It gets posted to HN and now I'm the bully for just wanting to protect myself.

Oh boy.

And why are you so upset about this, by the way?

**Comment by coleifer** [comment]
Oh, and by the way, the person who posted this to HackerNews under the title:

"Programmer banned from major open source project for calling bug “super weird”"

It turns out to be the **original bully**:

![s1468463589 59](https://cloud.githubusercontent.com/assets/119974/16826259/8c5f7ebe-4941-11e6-9249-cbf2d762af56.png)

**Comment by randalljason** [comment]
For the record, this buddy? https://www.google.com/search?q=keredson+peewee+site%3Agithub.com  Yeah, I can see why you banned him.  Reporting bugs such as "peewee should not gen SQL it knows is invalid"  What an a-hole.

My ban coming in 3... 2... 1...

**Comment by coleifer** [comment]
@randalljason: dude, that's not at all what I'm talking about. There are many issues reported by keredson that I fixed and discussed with him. Honestly man.

**Comment by dwelch2344** [comment]
Don't let the band wagon effect from HN get you down. You're running an OSS project, which is a hell of a lot more than most detractors will ever do. Keep it up!

**Comment by coleifer** [comment]
Thanks, friend! Appreciate you saying that.

**Comment by coleifer** [comment]
Thanks, friend! Appreciate you saying that.

**Comment by coleifer** [comment]
Not to sound paranoid, but I have a good feeling @randalljason is a sock puppet for a certain someone.

**Comment by coleifer** [comment]
This behavior is now fixed!

**Comment by nocivus** [comment]
Dude, it's your project! You can ban whoever you want. Forget the rest and keep working on your thing :)

**Comment by elcodedocle** [comment]
I'm sorry you feel you have to explain yourself from banning someone from contributing to your project. Open source projects thrive on contributions from the community and of course if you start banning people like crazy a fork or completely independent project will take over. That being said it is your project. Don't be afraid of managing it as you see convenient. Don't bother to explain what doesn't need to be explained to everyone involved enough. And fuck the critics. Even the positive ones.

**Comment by janus1337** [comment]
@coleifer, it's too bad this happened to you. I have been using peewee for a long time and you have always been one of the best maintainers I know of. Keep your head up you are doing awesome work.
