### ISSUE TITLE
Query doesn't work using `&`

### ISSUE THREAD

**Issue by Cee** [coleifer/peewee#1031]
```python
tweets_today = (Tweet
                .select()
                .where(
                    (Tweet.created_date >= datetime.date.today()) &
                    (Tweet.is_published == True))
                .count())
```

I'm a python beginner and follow the [example](https://github.com/coleifer/peewee/blob/master/README.rst), but I couldn't get a correct answer when I use `&` mentioned above. However, when I replace `&` with `AND`, it works.

**Comment by coleifer** [comment]
If I leave off the call to `.count()`, the SQL is:

```sql
SELECT "t1"."id", "t1"."user_id", "t1"."message", "t1"."created_date", "t1"."is_published" 
FROM "tweet" AS t1 
WHERE (("t1"."created_date" >= ?) AND ("t1"."is_published" = ?))
```

The parameters passed into the query are `[datetime.date(2016, 8, 8), True]`.

I believe you are mistaken. And I have *no* idea what you mean by "replacing it with AND" because "AND" is not valid Python. The `and` keyword is, but it does logical and (short-cutting), and cannot be overridden. Bitwise and `&` *can* be overridden, and is required when writing queries with Peewee.
