### ISSUE TITLE
pwiz not output models.py  with Mysql BLOB

### ISSUE THREAD

**Issue by rfyiamcool** [coleifer/peewee#1034]
pwiz not output models.py  with Mysql BLOB? 

parse error, My mysql filed is blob,  pwiz output TEXTFIELD .

Thanks U.

**Comment by coleifer** [comment]
The mapping in the `playhouse.reflection` module explicitly associates MySQL BLOB columns with `TextField`s. I wish I had left a comment as to why it is that way... There seems to be some odd behavior with the way MySQL / Python handle BLOBs compared to the other database engines Peewee supports out-of-the-box (the blob field test cases are skipped for MySQL). I've made a couple changes and will let the continuous integration run the tests and see what shakes out from there.

**Comment by coleifer** [comment]
If you take a look here, it seems to be a limitation of the Python MySQL drivers:

https://github.com/django/django/blob/master/django/db/backends/mysql/introspection.py#L15-L37

Note how all the `BLOB` types get mapped to `TextField` -- this is also the behavior of pymysql:

https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/constants/FIELD_TYPE.py

So rather than assuming BlobField everywhere, peewee does what Django does and assumes TextField. You can go back through the code and make replacements where needed, of course.
