### ISSUE TITLE
primary keys ignored in update queries

### ISSUE THREAD

**Issue by phryk** [coleifer/peewee#1068]
Primary keys are ignored (at least for ``CompositeKeyField``) when ``UPDATE``-ing rows.
I have a few "linker" tables that are just two ``ForeignKeyField`` used as ``CompositeKeyField``.
They are not editable due to this, since any call to ``.save()`` results in a syntax error in the query.

I pasted an example illustrating this behavior here: https://paste.xinu.at/Jz87/

Does peewee just not support updating primary keys due to potential consistency problems when using ``ForeignKeyField`` or is this a bug? I.e. do I have to work around this in my software or do you consider this something that falls under peewee's responsibility?

**Comment by coleifer** [comment]
When it comes to using composite primary keys, things like save() break down a bit because peewee doesn't know what exactly to do since the previous primary key values are gone from the model instance. The way it should work is that it would update, setting the new values and using the old values as the where clause. But when you change them, the old values are gone so peewee freaks out.

But changing primary keys is kind of a sign that maybe you should consider a different primary key.

**Comment by phryk** [comment]
I'm not editing for any real use-case, I'm just writing very generic software on top of peewee and noticed this behavior, which seemed weird to me - but it makes total sense now.
I'll look for a way to either nicely assert from a Model class whether this will happen or simply implement an immutability flag for Models like this.

Thanks for the info so early in the morning. :)
