### ISSUE TITLE
Playhouse extension for asyncpg

### ISSUE THREAD

**Issue by kolanos** [coleifer/peewee#1098]
Apologies if this has been asked already, but I would very much be interested in a playhouse extension for asyncpg:
https://github.com/MagicStack/asyncpg

Is this in the plans? Or better yet, if a PR was submitted to add asyncpg support would it be considered?

**Comment by coleifer** [comment]
The built-in async stuff all requires Python 3, and since Peewee supports both 2 and 3, any async will need to be implemented outside Peewee itself. I'd consider merging a `playhouse` extension, but as long as I'm still using Python 2 and `gevent`, I'm going to have trouble maintaining any 3.x-specific async code by myself.

There are some 3rd party libraries that implement async for Peewee, however:

* [peewee-async](https://github.com/05bit/peewee-async)
* [muffin-peewee](https://github.com/klen/muffin-peewee), integration with the async web framework [muffin](https://github.com/klen/muffin)

Hope that helps.

**Comment by coleifer** [comment]
Oh, I should add that psycopg2 does support async, so you can do something like this:

```python
import psycopg2
from psycopg2 import extensions

from gevent.socket import wait_read, wait_write


def monkey_patch():
    extensions.set_wait_callback(gevent_wait_callback)


def gevent_wait_callback(conn, timeout=None):
    while True:
        state = conn.poll()
        if state == extensions.POLL_OK:
            break
        elif state == extensions.POLL_READ:
            wait_read(conn.fileno(), timeout=timeout)
        elif state == extensions.POLL_WRITE:
            wait_write(conn.fileno(), timeout=timeout)
        else:
            raise psycopg2.OperationalError(
"Bad result from poll: %r" % state)
```

**Comment by kolanos** [comment]
@coleifer Ok, will make it an external extension for now. I did this with [peewee-momoko](https://github.com/txtadvice/peewee-momoko), but think it can be much improved with asyncpg and async /await.
