### ISSUE TITLE
select without commit?

### ISSUE THREAD

**Issue by knightliao** [coleifer/peewee#1207]
i found that every select sql will do commit at last in peewee.
this may cause transaction.

mybatis is a famous lib, it doesn't do transaction when it finds that select sql. 

will peewee implement " select without commit?" function?

**Comment by coleifer** [comment]
Peewee runs in autocommit mode unless you're within the scope of a transaction block, so any COMMIT issued as part of a SELECT query is occurring because a transaction is *not* active. If you're managing transactions outside of Peewee, then you may want to turn autocommit off (by passing `autocommit=False` in to the database constructor). I'd recommend against doing that, however.

Assuming you're running transactions using either the `atomic()` or `transaction()` helpers, then there's nothing to worry about.

**Comment by knightliao** [comment]
thanks a lot :)
