### ISSUE TITLE
[playhouse.dataset.DataSet] Cannot process column name contain "_"

### ISSUE THREAD

**Issue by renweibo** [coleifer/peewee#1275]
Here is the test case.
```python
    def test_case_1(self):
        db = DataSet('sqlite:///:memory:')
        books = db["books"]
        books.insert(book_id="ISBN1234567")
```
It should work but report following error:

```python
Traceback (most recent call last):
... ...
  File "/Users/renweibo/PycharmProjects/DailyNovel/common/test_driver.py", line 12, in test_case_1
    books.insert(book_id="ISBN1234567")
  File "/Users/renweibo/.virtualenvs/flask1/lib/python3.6/site-packages/playhouse/dataset.py", line 219, in insert
    return self.model_class.insert(**data).execute()
  File "/Users/renweibo/.virtualenvs/flask1/lib/python3.6/site-packages/peewee.py", line 4893, in insert
    fdict.update([(cls._meta.fields[f], insert[f]) for f in insert])
  File "/Users/renweibo/.virtualenvs/flask1/lib/python3.6/site-packages/peewee.py", line 4893, in <listcomp>
    fdict.update([(cls._meta.fields[f], insert[f]) for f in insert])
KeyError: 'book_id'
```

**Comment by renweibo** [comment]
Version:
- Python: 3.6.1
- peewee: 2.10.1

**Comment by coleifer** [comment]
The problem is the "_id" suffix. DataSet relies on the introspection tools in the `playhouse.reflection` module. These tools are used to read the database and generate peewee Model definitions. There's a convention in peewee, borrowed from Django, to append "_id" to foreign key fields. So if I have a Tweet and User model, and the Tweet.author is a foreign key to a User, the column will actually be called Tweet.author_id (though the field name is "author"). This comes into play when introspecting, which does the inverse -- if it sees a column named "xxx_id", it will strip the "_id" from the field name (preserving it for the column).

I'll look into how to fix this, at any rate.

**Comment by coleifer** [comment]
d68ae11501face8f4eb6adfde82d8eda79728dc7

**Comment by renweibo** [comment]
Thanks for the quick fix and support.

**Comment by coleifer** [comment]
For sure, thanks for the nice reports.
