### ISSUE TITLE
How much efficiency has been raised?

### ISSUE THREAD

**Issue by ilikeorange2006** [coleifer/peewee#1334]
I compiled _speedups.pyx at centos7, then try to fetch a whole table from MySQL database. I'm sure the speedups module was imported successfully, but it spent the same time as normal module. Does it work?

**Comment by coleifer** [comment]
So, the peewee 2.x speedups module should help noticeably with:

* Iterating over large result sets for simple selects (no joins) or when the return row type is `dict` or `tuple` (`.dicts()` or `.tuples()`).
* Resolving dependencies among a large number of models.

It's a pretty narrow range, and honestly, the gains are not that huge. With SQLite in-memory database containing 100K rows, iterating through them all yields:

- select models 5.412
- select dicts 4.114
- select tuples 4.231

And with speedups:

- select models 5.229
- select dicts 3.743
- select tuples 3.718

In the 3.x branch, there is no longer a "speedups" module simply because I didn't feel the maintenance burden of the additional code justified the tiny improvement. It was more of an experiment than anything else, I suppose.

Timings for 3.0a, just in case you were curious, are comparable to `master`:

- select models 5.751
- select dicts 4.268
- select tuples 4.271

**Comment by coleifer** [comment]
Here's the quick little script I put together to generate these numbers: https://gist.github.com/coleifer/7050c85d9e48dbe1307d7d648f7628a7

**Comment by ilikeorange2006** [comment]
Ah, I got it, thanks.
