### ISSUE TITLE
pwiz does not generate related_name argument

### ISSUE THREAD

**Issue by simopal6** [coleifer/peewee#1425]
As in the title, pwiz does not seem to use the `related_name` attribute on `ForeignKeyField`s. Is this expected? And is there a way to force it to do it?

**Comment by coleifer** [comment]
The related_name (backref in 3.0) is a property that only exists in python/peewee. It's not an actual database thing, just a convenient way to reference the set of referenced objects. What would you expect to happen?

**Comment by simopal6** [comment]
Sorry, I wasn't very clear. I have two tables, `video` and `frame` (as in "a video has many frames"), a foreign key constraint defined on `frame.videoid`.

When I run `pwiz`, it creates the models and adds the `ForeignKeyField` to the generated `Frame` class. However, no `related_name` argument is passed to `ForeignKeyField`, so I'm unable to easily access the frames associated to a given video from a `Video` model instance.

Of course I can easily modify the generated code and add the `related_name` argument myself, but I was wondering how come `pwiz` doesn't do it by itself.

**Comment by coleifer** [comment]
The `related_name` isn't explicitly defined because, if the user wants to use a non-default `related_name` pwiz has no way of anticipating what that might be.

The default related name/backref is "modelname_set", so in your case it would be `Frame.video_set` by default.

If you want something different then you'll of course need to edit the generated code.

**Comment by simopal6** [comment]
Ok, I see now. I didn't know that a default attribute on the "other" model would be created even without specifying `related_name` (I'm not sure this is documented). Thank you for your help!
