### ISSUE TITLE
Date storage and converstion

### ISSUE THREAD

**Issue by biskit** [coleifer/peewee#1581]
I have a date coming in like this '04/20/2018 7:52 PM'. It's stored in a DateTimeField column as is. So any comparison against datetime.now() fails (typically > some datetime).

**Comment by coleifer** [comment]
That format is no good because it doesn't sort lexicographically. Sqlite doesn't have a dedicate date/time data-type. You'll want to convert those to YYYY-mm-ddTHH:MM:SS so they sort correctly.

Peewee *can* read values like that if you specify the strptime format, however comparisons like the one in your example will not work correctly:

```python
lousy_datetime = DateTimeField(formats=['%m/%d/%Y %I:%M %p'])
```

It should be possible to also craft a one-time migration using sqlite's date/time functions: https://www.sqlite.org/lang_datefunc.html
