### ISSUE TITLE
different select behavior between 3.3.4 and 3.2.2

### ISSUE THREAD

**Issue by Trim21** [coleifer/peewee#1599]
I try some code like this
```python
# coding=utf-8

import peewee
from peewee import IntegerField, FixedCharField, TextField

db = peewee.SqliteDatabase('example.db')


class DB(peewee.Model):
    class Meta:
        database = db


class Table1(DB):
    name = TextField(unique=True, null=False)
    status = TextField()


class Table2(DB):
    user_name = TextField(unique=True)
    status = TextField()


if __name__ == '__main__':
    Table1.create_table(fail_silently=True)
    Table2.create_table(fail_silently=True)
    Table1.create(name='name', status='status_table_1')
    Table2.create(user_name='name', status='status_table_2')

    data = Table1.select(Table1, Table2.status) \
        .join(Table2, peewee.JOIN['LEFT_OUTER'], on=(Table1.name == Table2.user_name)) \
        .where(Table1.name == 'name').objects()
    print(data[0].status)
```
in peewee 3.2.2 it's `status_table_2`
but in peewee 3.3.4 it's `status_table_1`

I wonder is this a break change without change major version, or it's just a bug.

**Comment by Trim21** [comment]
I try many peewee versions, 3.2.4 is first version that return the values of table1 and 3.2.3 is the latest version that return the value of table2

**Comment by coleifer** [comment]
The change that was introduced was to avoid overwriting values. You're selecting all columns on `Table1` (including it's status field), so it's expected that the status field would contain the value on Table1.

To capture the status field on table 2 there are a number of things you can do:

* specify an alias for the Table2.status value (e.g. Table2.status.alias('status2'))
* if a foreign-key exists between the joined tables, look-up the attribute on the joined instance
* otherwise specify a join attribute by specifying an alias on the join predicate
