### ISSUE TITLE
I want to strip string values in my schema, what is the best way to achieve this?

### ISSUE THREAD

**Issue by moar55** [coleifer/peewee#1717]
I thought of using the `pre_save` but I am not sure if this is the optimal method.

**Comment by coleifer** [comment]
Presumably you would do any data-processing before throwing it into Peewee...Peewee is your layer for talking to the database, in a clean design it should probably not also be your business-logic layer. You're probably best off just overriding the `save()` method rather than messing with the signals API, though of course that's an option.

**Comment by moar55** [comment]
Thanks!
