### ISSUE TITLE
TimestampField appears to strip milliseconds

### ISSUE THREAD

**Issue by tbaxter-18f** [coleifer/peewee#1747]
given a timestamp like 1419440770.000058 when I create the object, the timestamp appears to be stored as 1419440770, with no milliseconds present any longer.

**Comment by coleifer** [comment]
Well, here's the thing. Peewee's `TimestampField` is designed to work with python `datetime` objects, which is typically what you want in your application code -- it just uses an integer timestamp for storage. That being said, you still *can* specify integer / floating-point timestamps. For sub-second resolutions you will just need to also specify the desired resolution when instantiating the field, expressed as a power-of-10. This works because behind-the-scenes Peewee just multiplies the timestamp by a power-of-10 to obtain an integer.

```python
class Event(Model):
    timestamp = TimestampField(resolution=1e6)  # microseconds.
    data = TextField()

# We can specify an integer or floating-point timestamp -- peewee will do the right thing:
ts = 1500000000.123456  # 2017-07-13 21:40:00.123456
Event.create(timestamp=ts, data='event-1')

# Or we can just use a datetime object:
dt = datetime.datetime(2018, 1, 2, 3, 4, 5, 6789)
Event.create(timestamp=dt, data='event-2')

# Peewee converts to datetimes when reading from the db:
for event in Event.select():
    print(event.data, ':', event.timestamp)

# Prints:
# event-1 : 2017-07-13 21:40:00.123456
# event-2 : 2018-01-02 03:04:05.006789
```
