### ISSUE TITLE
WHERE TRUE condition

### ISSUE THREAD

**Issue by againagainst** [coleifer/peewee#1841]
Is there any possibility to make the simple `TRUE` condition for where clause? I would like to use it as an initial condition and combine with some extra conditions if necessary:
```
    def get_users(self, removed=False, deactivated=False):
        cond = Model.TRUE
        if removed:
            cond &= ~(Users.removed >> None)
        ...
        return [to_dict(user) for user in Users.select().where(cond)]
```

**Comment by coleifer** [comment]
Eh, you can do `Value(1) == Value(1)`...but the way I would handle that is to accumulate a list and then use `reduce`, e.g.:

```python
from functools import reduce
import operator

# ...

expr_list = []
if removed:
    expr_list.append(User.removed.is_null(False))
if deactived:
    expr_list.append(User.active.is_null(True))
# ...
query = User.select()
if expr_list:
    query = query.where(reduce(operator.and_, expr_list))
return query
```

A couple notes on your code, by the way:

* `~(Users.removed >> None)` is NOT the same as `IS NOT NULL`. It is `NOT (... IS NULL)`. Better to use `User.removed.is_null(False)` which translates to Users.removed IS NOT NULL.
* It is recommended never to use plural for model names. Better to use `User`.
* Returning a query is always more flexible. Rather than return a list of dicts, return a query, and only convert to a list-of-dicts at the last possible moment.
