### ISSUE TITLE
NULLS not supported on SQLite

### ISSUE THREAD

**Issue by mkoura** [coleifer/peewee#1877]
Syntax like `ORDER BY somevalue DESC NULLS LAST` doesn't work on SQLite. We are using `column.desc(nulls='LAST')` in one of our models and when using SQLite (for unit testing), this fails with

```
Traceback (most recent call last):
  File "<venv>/lib64/python3.7/site-packages/peewee.py", line 2835, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: near "NULLS": syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
  File "<venv>/lib64/python3.7/site-packages/peewee.py", line 2835, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: near "NULLS": syntax error
```

I didn't find any mention that `nulls` argument is PostgreSQL specific so I assume this behavior is a bug.

**Comment by coleifer** [comment]
NULLS is not supported by Sqlite. For SQLite you can use a case expression, however: http://docs.peewee-orm.com/en/latest/peewee/api.html#Case

**Comment by coleifer** [comment]
I've added a feature check and compatibility layer so that you can specify ``nulls='first'`` or ``nulls='last'`` with any database, and Peewee will generate the appropriate SQL. For postgres, it uses the usual non-standard ``nulls first/last``, but for sqlite and mysql, an equivalent ``CASE`` statement will be generated.

**Comment by mkoura** [comment]
Awesome, thanks a lot!
