### ISSUE TITLE
[Question] how to insert literal sql fragment to query

### ISSUE THREAD

**Issue by james-lawrence** [coleifer/peewee#1908]
how does one express:
`SELECT * FROM table WHERE timestamp > '-infinity';`
or
`INSERT INTO table (...., col1) VALUES (....) ON CONFLICT (id) DO UPDATE SET col1 = DEFAULT;`

w/ peewee?

**Comment by coleifer** [comment]
For the first one, depends on the data-type of the timestamp column, the database driver and the db you're using. You can try using `.where(MyModel.timestamp > float('-inf'))` but it may or may not work. A much saner way would be to use `datetime.datetime.min` instead of "-infinity".

For insert / on conflict, there are [extensive docs](http://docs.peewee-orm.com/en/latest/peewee/querying.html#upsert) along with [API documentation](http://docs.peewee-orm.com/en/latest/peewee/api.html#Insert.on_conflict).

To reference the default, you can use `SQL('DEFAULT')`, e.g.:

```python

Table.insert(id=1, col1='foo').on_conflict(
    conflict_target=[Table.id],
    update={Table.col1: SQL('DEFAULT')})
```

Also, please read the documentation. I've clearly requested that, if you have questions, you do not open github issues: http://docs.peewee-orm.com/en/latest/peewee/contributing.html#questions -- stackoverflow, the mailing-list, and the irc channel are all good places to ask questions.

**Comment by james-lawrence** [comment]
note: i believe peewee.AsIs('-infinity') and peewee.AsIs('DEFAULT') is solving me issue. but I find no reference to the method in the documentation.

**Comment by coleifer** [comment]
That's fine, or `SQL('-infinity')` / `SQL('DEFAULT')` would probably be the more usual way.

**Comment by james-lawrence** [comment]
I had issues w/ SQL inproperly quoting '-infinity'. that was the first thing I tried. ./shrug.

**Comment by james-lawrence** [comment]
```
Model.select().where(Model.timestamp > peewee.SQL('-infinity')).execute()
```

fails with `peewee.ProgrammingError: column "infinity" does not exist` because it doesn't quote.
and if you try to force the quotes it starts escaping them (which is fine btw)

```
Model.select().where(Model.created_at > peewee.AsIs('-infinity')).execute()
```
succeeds because it quotes.

the fact AsIs isn't anywhere in the documentation lead to the issue being filed.

**Comment by coleifer** [comment]
> the fact AsIs isn't anywhere in the documentation lead to the issue being filed.

And yet your issue makes no mention of `AsIs` until we get down to the comments.

Did you try `Value('-infinity')` ?
