### ISSUE TITLE
[Question] Extending Query class to add new query clause

### ISSUE THREAD

**Issue by DpodDani** [coleifer/peewee#1911]
Hey,

First of all, thank you for creating this wonderful Python database interface API, it has been fun and educating tinkering around in the code base.

This is not really an issue, but more of a question. I am trying to extend Peewee to work with a SQL Server database, however I cannot seem to figure out how to implement a TOP clause - as in `SELECT TOP 10 name from [db].[schema].[table]`. How do you suggest I go about this?

Thank you,
Daniel

**Comment by coleifer** [comment]
Well, the easiest way of course is just to use the `SQL()` helper to insert the sql literal directly (SQL() also supports parameterization):

```python

query = MyModel.select(SQL('TOP 10'))

query = MyModel.select(SQL('TOP %s', (10,)))
```

But more generally to be able to translate a call to `.limit(10)` method, you will probably have a hard time. Unfortunately, at this time, Peewee doesn't provide the level of flexibility in overriding the essentials of the query-building APIs. That's because Model.select delegates to a ModelSelect which extends Select, etc., and it's not straightforward how one would generalize a change to the query building. You could subclass Model and override the select classmethod to provide your own implementation of ModelSelect, of course.

**Comment by DpodDani** [comment]
Thank you. I will play around with those suggestions 👍
