### ISSUE TITLE
Improve equality check

### ISSUE THREAD

**Issue by clintonb** [coleifer/peewee#1993]
The current implementation of `__eq__` on `Model` just checks if the primary keys are equal.
https://github.com/coleifer/peewee/blob/f6d693366eccb8e27b0b331246358f9c7d4e54b7/peewee.py#L6364-L6368

It would be preferable to if this method compared the value of all fields.

Test case:
```python
from models import Test
t1 = Test(id=1, foo='bar')
t2 = Test(id=1, foo='apple')
assert t1 != t2
```

Context: When writing tests, I prefer to compare two instances rather than iterate over all of the fields.

**Comment by clintonb** [comment]
Here is a proposed implementation:

```python
def __eq__(self, other: Any) -> bool:
    if not super().__eq__(other):
        return False

    for field in self._meta.sorted_fields:
        if getattr(self, field.name) != getattr(other, field.name):
            return False

    return True
```

**Comment by coleifer** [comment]
I can't imagine a situation in practice where such a comparison would be valuable. It suggests to me that there's a problem elsewhere in the implementation of your code. Models are not a representation of the state of the DB at all times. It's just simple active record. As such, comparing IDs seems reasonable but it's best to never need to compare model instances at all because of this.
