### ISSUE TITLE
TimestampField uses an undocumented power of 10

### ISSUE THREAD

**Issue by Sekenre** [coleifer/peewee#2009]
If I create a TimestampField(resolution=1) it will unexpectedly multiply the timestamps by 10.

This is different from the default resolution of 1 second if the resolution is set to None.

Resolution as a power (`10 ** x`) where x is in `range(7)` is undocumented and maybe a bit confusing. To resolve this in my own code I had to set `resolution=0` which will make it harder for someone to read my intent.

**Comment by coleifer** [comment]
Originally this was expressed as 1, 10, 100, ... 1000000. I added the option to provide it as the exponent instead, but this broke the default of 1 (turning it into 10).

Fixed so that 0 and 1 both resolve to seconds resolution. To get 10th of a second, one needs to supply the resolution=10, but I don't think this is likely to be an issue. People tend to either use seconds, milliseconds or microseconds.
