### ISSUE TITLE
inserting silently fails

### ISSUE THREAD

**Issue by DavHau** [coleifer/peewee#2101]
python: 3.7
peewee: 3.13.1

The following code fails to insert without any notice:
```python
from peewee import *

db = SqliteDatabase(f'test.db')

class BaseModel(Model):
    class Meta:
        database = db

class Script(BaseModel):
    name = CharField()
    version = CharField()
    script = TextField(null=True)
    class Meta:
        primary_key = CompositeKey('name', 'version')

db.connect()
db.create_tables([Script])

Script(name="test", version="1.1.1", script="test script").save()
print(Script.select().exists())
```

**Comment by coleifer** [comment]
When you have a primary key that is not autogenerated, you need to specify `force_insert=True` when saving.

http://docs.peewee-orm.com/en/latest/peewee/models.html#id4

Here's my advice: don't use composite keys. Just use the standard autoinc primary key and use a multi-column unique constraint. You'll have a **much** better time.

Peewee doesn't support foreign keys to composite primary keys, either, which sometimes trips people up.

Lastly, Google before you post, because this is heavily traveled ground
