### ISSUE TITLE
Add model information to DoesNotExist

### ISSUE THREAD

**Issue by conqp** [coleifer/peewee#2327]
Currently it is hard to extract model context from generic `DoesNotExist` exceptions.
It would be nice, if the `DoesNotExist` class would have information about the model, so I can do something like this:

```python
from flask import Flask
from peewee import DoesNotExist, Model, ModelBase

APPLICATION = Flask('myapp')

@APPLICATION.errorhandler(DoesNotExist)
def no_such_model(exception: DoesNotExist):
    return (f'Model {exception.model} does not exist.', 404)
```

Currently I have to write such a handlers for every single `Model.DoesNotExist` to have the context of which model was not found.

**Comment by coleifer** [comment]
This seems of somewhat questionable utility as it seems more likely you would want to catch- and handle those exceptions rather than bubbling them all the way up to the web framework to handle generically. I'm going to pass on this for now, but will keep an eye out for other requesters/use-cases for this and re-evaluate then.

**Comment by conqp** [comment]
Fair enough. My current code is currently working with separate handlers for each model's exception.
I just see this as a means of reducing duplicated code.
