### ISSUE TITLE
distinct() on a ModelCompoundSelectQuery raises an error

### ISSUE THREAD

**Issue by arel** [coleifer/peewee#2335]
I am using peewee version 3.14.0. A see that `ModelCompoundSelectQuery` does not have a `distinct()` method, and calling it raises the error:

```
AttributeError: 'ModelCompoundSelectQuery' object has no attribute 'distinct'
```

For example:

```python
o1 = User.select().where(User.id < 5)
o2 = User.select().where(User.id > 1)
o3 = o1 | o2

query1 = o1.distinct()  # OK
query2 = o3.distinct()  # Raises error
```

I would expect a compound query to have the same API as any query. If this expected behavior, how should one select distinct rows in a compound query?

**Comment by coleifer** [comment]
This is because the convention is different when using UNION and UNION ALL. From which side of the union would you be selecting "distinct" from, in your example? You could put distinct on both the left- and right-half of the query, but I think what you want is actually just the regular behavior of UNION.

See this answer: https://stackoverflow.com/questions/49925/what-is-the-difference-between-union-and-union-all

Or https://www.w3schools.com/sql/sql_ref_union.asp
