### ISSUE TITLE
add_column only applies default value if column does not allow null

### ISSUE THREAD

**Issue by feixie** [coleifer/peewee#2352]
I would like to add columns that allow nulls AND have a default value. While I can define columns with default values and null=True when I create the table, I can't do it via add_column because this line: https://github.com/coleifer/peewee/blob/master/playhouse/migrate.py#L329 only applies the default value when the field is not nullable.

**Comment by coleifer** [comment]
The `apply_default()` method is exposed as an operation, just like `add_column()`. Since "defaults" specified this way are implemented in Python rather than as a sql default constraint, I've avoided automatically applying them when the field is left nullable (as this implies an UPDATE of every row of the table).

So you would:

```python

migrate(
    migrator.add_column('my_tbl', 'my_col', field_obj),
    migrator.apply_default('my_tbl', 'my_col', field_obj),
)
```
