### ISSUE TITLE
AttributeError with multiple ForeignKeyField to the same table.

### ISSUE THREAD

**Issue by andmart** [coleifer/peewee#236]
Charles,

Here a simple example to reproduce:

``` python
from peewee import *

class Parent(Model):
    name = CharField()

class Student(Model):
    name = CharField()
    father = ForeignKeyField(Parent)
    mother = ForeignKeyField(Parent)
```

```
AttributeError: Foreign key: student.mother related name "student_set" collision with foreign key using same related_name.
```

It seems that peewee tries to make a set with all the references to same table, but there is case where the attributes are different.

**Comment by teeberg** [comment]
I agree that it would be nice if pwiz generated working models out of the box, no matter the names. Couldn't it simply use the field name of the referenced model to this effect, i.e. set it as a default `related_name`? Whether it's `father_students`, `fathers`, `mother_students` or what not wouldn't really matter since you can always change it when you find it too awkward.

**Comment by coleifer** [comment]
I'll look into it, but I'm going to go out on a limb and say that ``pwiz`` does a pretty damn good job at what it does.

**Comment by teeberg** [comment]
I agree! I actually just found out about peewee and used it to generate models for quite large existing databases. With search/replace, I had fixed all problems within minutes. I'm already pretty amazed as it is! This is awesome! :-)
