### ISSUE TITLE
Does peewee create MySQL conn object every time a query execute?

### ISSUE THREAD

**Issue by zhuyanxi** [coleifer/peewee#2367]
https://github.com/coleifer/peewee/blob/ac5126d774d89b07b3e8ccb871897e9a0bf53fde/peewee.py#L3972
I find that in the `MySQLDatabase` class , it will create MySQL conn object every time the function `_connect` executed:
```python
def _connect(self):
        if mysql is None:
            raise ImproperlyConfigured('MySQL driver not installed!')
        conn = mysql.connect(db=self.database, **self.connect_params)
        return conn
```

And now my situation is: I have a MySQL DB in AWS North America, and my frontend app is in China. After I had a test, I found that each time I send a request, there was 2 steps: first connect to the MySQL DB take about 350ms, and then second execute the sql command takes another 350ms, that make my app a little bit slow. 

So I think may it's better to hold a `conn` object in memory for a while and reuse it than to create a `conn` object every time.

And My question is:
Is there a way to make the `MySQLDatabase` reuse the `conn` object? Or should I need to extend the `MySQLDatabase` class myself?

**Comment by coleifer** [comment]
If you had spent your time investigating rather than posting this issue, you would find:

This is also documented rather extensively: http://docs.peewee-orm.com/en/latest/peewee/database.html#connection-management

If you want to reuse a connection, then you should use the connection pool, which is mentioned in the above document and also extensively documented:

* http://docs.peewee-orm.com/en/latest/peewee/database.html#connection-pooling
* http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#pool
