### ISSUE TITLE
PostgreSQL Autoreconnect / migrations

### ISSUE THREAD

**Issue by konradkur** [coleifer/peewee#2405]
Hello guys,

i try find solutions for postgresql autoreconnect, any ideas?

next question, the best migration system for peewee it?

thanks,
Konrad

**Comment by coleifer** [comment]
Automatic reconnect can be done with the help of the `playhouse.shortcuts.ReconnectMixin`, but you will definitely need to modify the `reconnect_errors` attribute so that it corresponds to Postgres-specific error conditions. The reconnect mixin should not be used with Postgres unless you REALLY know what you are doing. See the source code: https://github.com/coleifer/peewee/blob/master/playhouse/shortcuts.py

Peewee provides a helper for writing migrations: http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#schema-migrations

I can't vouch for any of the "automatic" migration tools.
