### ISSUE TITLE
Is JSONPath for postgresql support planned?

### ISSUE THREAD

**Issue by DimaKalbfleysh** [coleifer/peewee#2416]
Colleagues, good afternoon, JSONB has become an integral part of many projects. And I believe that many would like to see the implementation of this functionality (JSONPath) in peewee!

**Comment by coleifer** [comment]
There is some simple jsonpath support for the `__getitem__()`-type operations on jsonb fields. Because jsonpath is basically an entire language of its own, I've chosen not to implement some kind of python layer for now.

You can call the postgres jsonpath functions quite easily from peewee via `fn.jsonpath_XXX()` and pass in the field instance and the desired path as a string.
