### ISSUE TITLE
Some obstacles when trying to add a driver for ClickHouse 

### ISSUE THREAD

**Issue by pm5** [coleifer/peewee#2435]
I saw #912 and tried to add a driver for [ClickHouse](https://clickhouse.tech/) using [clickhouse-driver](https://clickhouse-driver.readthedocs.io/en/latest/features.html#python-db-api-2-0) but there seems to be some obstacles:

- The [documentation](http://docs.peewee-orm.com/en/latest/peewee/database.html#adding-a-new-database-driver) seems outdated.  `Database._connect` is no longer taking arguments and one has to use `foodb.connect(self.database, **self.connect_params)` instead.
- The DB API 2.0 implemented by clickhouse-driver specifically uses Python extended format codes for SQL parameters, i.e. `%(name)s`, which is [allowed](https://www.python.org/dev/peps/pep-0249/#paramstyle).  I've found `Database.param` in peewee, but it seems a bit hard to get it work with this format.

Any suggestions?

**Comment by coleifer** [comment]
I've fixed the first item, thank you for bringing that to my attention.

The second item will not be so easy, since it implies that you are passing the parameters as a `dict`. Every other driver I know of just uses a tuple to represent the query parameters, so there is probably some work involved in getting this working. It looks like this driver is implemented very idiosyncratically compared to the others, e.g.

```
>>> cursor.executemany('INSERT INTO test (x) VALUES', [[200]])
```

What the heck is going on here? Is the driver inserting placeholders?

I'd suggest taking it up with the clickhouse implementer(s) to see about getting this resolved upstream, as it will likely be rather tricky with Peewee.
