### ISSUE TITLE
migrate leave foreignkey  out of consideration

### ISSUE THREAD

**Issue by woshimanong1990** [coleifer/peewee#2439]
I drop a field to a tabel ,but not I success. Finally, I found, it's a bug.
you create a tmp table and then, drop old tabel. BUT, leave foreignkey  out of consideration
`      
        # Find any foreign keys we may need to remove.

        self.database.get_foreign_keys(table)
`

do nothing
I used sqlite.
maybe I should use `PRAGMA foreign_keys=OFF` first

**Comment by coleifer** [comment]
The foreign keys are returned by `pragma foreign_key_list("...")`. I'm not sure I understand the issue you're describing.

**Comment by BranislavBajuzik** [comment]
I think he meant that in the `playhouse.migrate.SqliteMigrator._update_column` there is a piece of code that seemingly does nothing as the return value is ignored:
```python
        # Find any foreign keys we may need to remove.
        self.database.get_foreign_keys(table)
```

Now my problem is a _bit_ different. I am also unable to drop a FK column in a SQLite database. 
I pass the check in `playhouse.migrate.SqliteMigrator.drop_column`; ` if sqlite3.sqlite_version_info >= (3, 35, 0)` because my version is `(3, 37, 2)`. However, I get an error from the database, stating: 
```
error in table foo after drop column: unknown column "bar_id" in foreign key definition
```
The SQL that caused this is `ALTER TABLE "foo" DROP COLUMN "bar_id"`

I got the migration working by forcing the version check to fail by forcing legacy mode.\
(This means that the `get_foreign_keys` either does something or is not needed)

Now, my question/issue is: Why does the `ALTER ... DROP` get used if it fails? Is there something wrong with my setup, or is that functionality simply not present in the lib? 

```
peewee                  3.17.6
peewee-migrate          1.12.2
```
