### ISSUE TITLE
Consider exposing the underlying query in `prefetch()`

### ISSUE THREAD

**Issue by ilyakamens** [coleifer/peewee#2608]
Mr. Leifer,

Thanks for creating and maintaining such a great library. We've used it at Propel since August 18, 2015 starting with version 2.6.2.

I'd like to use `prefetch()` to avoid N+1 queries, but am having trouble doing so because `prefetch()` returns a list instead of a query. We use peewee queries (e.g., `User.select().where(...)`) as part of a generalized data migration system. Here's what some of the code in that system looks like:

```python
if checkpoint:
    checkpoint_id = self.checkpoint_to_id(checkpoint)
    query = query.where(query.model.id > checkpoint_id)

rows = list(query.order_by(query.model.id).limit(batch_size))
modified = pool.imap(lambda row: self._migrate_row(row, dry_run), rows)
```

As you can see, a list of peewee models is difficult to integrate into this API. Would you consider some kind of non-breaking API change to enable access to the underlying `prefetch()` query? Something like `prefetch_query()`, or perhaps a `kwarg` like `query=True` (or whatever you're amenable to)? I'd also be happy to submit a PR.

Thanks again.

**Comment by coleifer** [comment]
Prefetch does not expose a query because the results are not composed of a single query, but rather `k` queries for however many tables are being prefetched. Dependent rows are iterated and an in-memory map is built for efficiently assigning them to their parent model instance/row. They're not able to be composed like your usual peewee queries.

Also note, I'd advise profiling to make sure `prefetch()` is actually faster in your case. It will likely come down to the ratio of the sizes of your outermost -> innermost loops whether it even provides a speedup or not.

**Comment by ilyakamens** [comment]
What's the value of `pq.query` before it's wrapped in a list [here](https://github.com/coleifer/peewee/blob/b36aea92d5c111278a9d0649afab89f9f1ffe0ac/peewee.py#L7934)?

**Comment by coleifer** [comment]
These lines are more relevant https://github.com/coleifer/peewee/blob/b36aea92d5c111278a9d0649afab89f9f1ffe0ac/peewee.py#L7927-L7932 but that is the outermost query, which has already been consumed and all the cached row instances in its CursorWrapper have their related child-instances populated, and so-on down the chain.
