### ISSUE TITLE
PostgresqlDatabase multithreading performance problem

### ISSUE THREAD

**Issue by mohamin1995** [coleifer/peewee#2655]
i have a postgresql db connection:

**Comment by mohamin1995** [comment]
@coleifer

**Comment by mohamin1995** [comment]
I implemented the multi process version too but the problem still persist with peewee then I implemented the function using psycopg2 adapter and the performance became 4 times faster(with multi threading).
@coleifer

**Comment by coleifer** [comment]
Was it also 4x faster single-threaded with psycopg2?

**Comment by coleifer** [comment]
I made a little script that inserts 100K rows and queries it single-threaded, using 4 threads and 4 processes. The single-thread and 4-thread run about the same, but the multiprocess version runs in about half the time.

The psycopg2-only version is faster, but this is somewhat expected since it carries none of the python-side overhead. It is also marginally faster (10%) when run multi-threaded.

I profiled the code and it looks to me like the bulk of the time in peewee is spent generating sql and serializing result rows to model instances, which is to be expected.
