### ISSUE TITLE
Automatic Migrations Capability

### ISSUE THREAD

**Issue by anuran-roy** [coleifer/peewee#2716]
Hey there!

Anuran this side! I'm a long time fan of peewee, been using it for a quite a few projects - thanks for this awesome tool, really saves a lot of time for someone who uses Django as well! 🚀 

Actually I was on the process of creating a custom script for automated migrations, since I couldn't find any automated tool for migrations, so I decided to create one. I was going through the codebase of peewee - it's pretty neat.

I wonder why an automated migrations haven't been added yet, especially given that `playhouse.migrate` does exist.

Can I go forward and develop an `AutoMigrator` object, that depends on the objects provided by `playhouse.migrate`?

**Comment by coleifer** [comment]
>since I couldn't find any automated tool for migrations

You may not have looked very hard, there are several I'm aware of:

* https://github.com/klen/peewee_migrate
* https://github.com/aachurin/peewee_migrations
* https://github.com/timster/peewee-moves

I can't vouch for the fitness or suitability of any of the above, but they all seem to offer automatic migrations in some form.

>why automated migrations haven't been added

Because I don't believe they actually save much time, and that writing an explicit migration using the migrator module is preferable. Not everyone agrees with me, hence the above list. I have no plans on integrating such functionality into peewee, however.

**Comment by anuran-roy** [comment]
I actually found only aachurin/peewee_migrations and it seems to be inactive, so I raised the issue. Thanks for the clarification!
