### ISSUE TITLE
Instance based database connections based on the same model?

### ISSUE THREAD

**Issue by BatPandaPancake** [coleifer/peewee#2722]
I'm writing a library of sorts that will allow the user to create various objects with lists. Each user-object will have an instantiated "IndexHandler" object that will handle the sqlite database stuff. Most importantly each IndexHandler and thus parent user object will have its own database based on the name the user instantiated their parent object with.

The big issue is that the IndexHandlers will all be using the same peewee model which is by design bound to a single database. I don't like the idea of checking and swapping databases all the time , and simply copy pasting the model and renaming it would limit the user's objects to however many I duplicated.

I'm wondering if making the peewee model an inner class of the index handler would work, or if you have any other suggestions on how to go about this.

Thanks!

**Comment by coleifer** [comment]
>I'm wondering if making the peewee model an inner class of the index handler would work, or if you have any other suggestions on how to go about this.

Yes, this is a fine idea, assuming the user's database lives there as well. Typically I'd declare the models in a constructor or helper function and set them as attributes on the instance of the `IndexHandler` or what-have-you (rather than putting them at class-level scope, which is evaluated at run-time).

I've done applications somewhat like this before and have done the above (or closed-over some particular piece of information and then declared and returned the model from the closure).

There are other ways to leverage python's dynamism, but I won't get into it since it seems like you've already struck upon a good idea.

**Comment by xloem** [comment]
Would this be simplified by providing to pass a database to constructor functions like `Model.get_or_create` ?
