### ISSUE TITLE
How to simply replace in postgres?

### ISSUE THREAD

**Issue by hykilpikonna** [coleifer/peewee#2760]
If I write `Model.replace(...).execute()` for postgres, it will throw the error "The only supported actions for conflict resolution with Postgresql are "ignore" or "update"."

If I do insert with on_conflict preserve all other fields, it works but that's like really long, and there doesn't seem to be a way to easily put in all fields of a mode for preserve either.

![image](https://github.com/coleifer/peewee/assets/22280294/bcd38549-2002-4b55-92f6-e85abf61b711)

**Comment by coleifer** [comment]
Yeah, postgres does not provide a very friendly syntax for these operations. The reason we can't just use `replace()` is because of the need to specify the conflict target -- this is annoying, but it's just how postgres works.

So you can shorten this somewhat:

```python
(DailyXP
 .insert(...)
 .on_conflict(
    conflict_target=[DailyXP.duo_id, DailyXP.date],
    preserve=DailyXP._meta.sorted_fields)
 .execute())
```

You can wrap all this up in a classmethod on your class.
