### ISSUE TITLE
Incorporating pgvector for document/similarity search?

### ISSUE THREAD

**Issue by bgriffen** [coleifer/peewee#2761]
I've been using peewee for a number of projects but one thing I can't use it for is performing document similarity queries using NLP embeddings (e.g. from spacy). I was wondering if anyone had looked at including [pgvector](https://github.com/pgvector/pgvector) into the peewee extensions. There is already this [pgvector-python](https://github.com/pgvector/pgvector-python) package that looks nearly ready to go without too much headache? I'm unsure of the logistics of incorporating into peewee. I'm not adept enough to include this on my own unfortunately but would seem like a very useful inclusion for the postgres extensions.

**Comment by coleifer** [comment]
I'd recommend having the extension added in `pgvector-python` since it looks like they support some other orm's out there. It should be quite simple. There are some [docs](http://docs.peewee-orm.com/en/latest/peewee/models.html#creating-a-custom-field) for creating a custom field, as well as examples here: https://github.com/coleifer/peewee/blob/master/playhouse/postgres_ext.py#L253-L295

HStoreField is a decent example, I think, because it shows how to deal with custom infix operations as well as lists of values.
