### ISSUE TITLE
SQLite: unable to manage datetime objects with ISO-formatted representation

### ISSUE THREAD

**Issue by passiomatic** [coleifer/peewee#2837]
Hi, recenty I've stumbled into a weird issue using Peewee 3.x. ISO-formatted (`YYYY-MM-DDTHH:MM:SS`) datetimes values coming from a Flask application in JSON format were incorrectly recognized as such when deserialized from local sqlite database.

The related sqlite [docs on the subject][1] suggests that sqlite understands ISO-formatted datetimes in the following formats:

```
YYYY-MM-DD HH:MM
YYYY-MM-DD HH:MM:SS
YYYY-MM-DD HH:MM:SS.SSS
YYYY-MM-DDTHH:MM
YYYY-MM-DDTHH:MM:SS
YYYY-MM-DDTHH:MM:SS.SSS
```

If my analisys is correct it looks like Peewee limits the recognized formats to https://github.com/coleifer/peewee/blob/master/peewee.py#L5284. I'm wondering if this done on purpose (maybe to maintain some backwards compatibility with older sqlite version?) or could be the formats extended to include _all_ the above variations?

In the meantime I've managed to fix my issue by seriaziling datetime without the `T` separator using a custom JSON encoder, but I would like to use more standard datetime representation in the future.

Thank you.

[1]: https://www.sqlite.org/lang_datefunc.html

**Comment by coleifer** [comment]
Peewee uses the `' '` separated format because that's the default that Python uses when converting a `datetime` to a string. We avoid specifying additional formats out-of-the-box due to the fact that each must be tried when converting the value from Sqlite back to Python. The standard library Sqlite driver converts `datetime` objects using this representation, so datetime values written from Python -> Sqlite will end up using the whitespace separator.

If you wish to, you can subclass and override the `formats` parameter on `DateTimeField` to include the ISO. You will also probably want to also ensure that the values, when written back, are also serialized using the "T" separator. This can be done by also overriding the `db_value()` method to return `value.isoformat()`.
