### ISSUE TITLE
Support for JSONB in SQLite

### ISSUE THREAD

**Issue by damascene** [coleifer/peewee#2862]
Seems like SQLite added support for JSONB

https://www.sqlite.org/json1.html#the_jsonb_format

Is it possible to use JSONB with SQLite in Peewee or is there any plan to support it? Wasn't able to find info about it in the documentation. 

https://docs.peewee-orm.com/en/latest/peewee/sqlite_ext.html#sqlite-json1

**Comment by coleifer** [comment]
It doesn't really work quite the same as you would think, as storing it in `jsonb` will return the data as a blob. It's necessary to always/explicitly convert the values -- rather than thinking of jsonb as a full data-type, it's more like a special representation that can be accessed in certain ways with special functions. That said, for users who are willing to use this carefully and correctly, I've added some initial support:

adad27b0ba6086bd02cd7273d13c6f3e8bc3d08c

**Comment by damascene** [comment]
Thank you will take your comments into account d.v.
