### ISSUE TITLE
Regression of < used on connections

### ISSUE THREAD

**Issue by antoyo** [coleifer/peewee#2901]
Hi.
[This commit](https://github.com/coleifer/peewee/commit/ea3fb11a9c2a4b0cd958a453dd287e408477eda5) seemed to have reintroduced the bug #1883.
I haven't really tested the previous commit, but version 3.17.0 works for me.
Thanks to fix this issue.

**Comment by coleifer** [comment]
I'm at a bit of a loss how to replicate this. Where are you seeing the traceback, when calling `close()` to check the connection back in? Is it possible that the timestamps are identical? The only change I can think that would affect you is the removal of the random "jitter" added to the timestamps.

**Comment by coleifer** [comment]
The only way I could replicate was by monkey-patching `time.time()` to return the same timestamp. I suppose if the operating system time resolution is seconds, e.g. per Python docs:

>Note that even though the time is always returned as a floating point number, not all systems provide time with a better precision than 1 second.

It is possible this would occur with much greater likelihood. I wonder if that's the case on the system you're using.

Instead of using randomness, I've just inserted into the heap a comparable no-op. That should fix things fairly robustly.

**Comment by antoyo** [comment]
Here's what `time()` returns on my system:
```
>>> time()
1716389563.1667016
```
I'll try this commit and see if that fixes my issue.

**Comment by coleifer** [comment]
Can you please provide some indication, then, how you encounter or replicate this?
