### ISSUE TITLE
SQL Server Support

### ISSUE THREAD

**Issue by source19069** [coleifer/peewee#2937]
Hello

A bit of background. We in research at the Boston Veterans Health Administration have a product call Prodigy from explosion.ai that we use for annotating text to use to train NLP models. Prodigy uses peewee, but our security infrastructure standards require us to place data into SQL Server databases. Open source DBs such as MySQL, etc that peewee supports cannot be used.

We'd like to build SQL Server support into peewee and contribute to your effort. Creating a Database class and a Dialect seem to be what is required to implement SQL Server support in peewee, at a minimum.

Can you tell us precisely what we need to provide you to integrate our code into peewee? What are your expectations for contributors?

Thank you.

**Comment by coleifer** [comment]
There is some documentation describing what is necessary: http://docs.peewee-orm.com/en/latest/peewee/database.html#adding-a-new-database-driver

I know for sure you're going to have a bit of work to do to get peewee to work w/MS-SQL's OFFSET x FETCH FIRST y syntax (or SELECT TOP x) as that isn't going to be straightforward due to the design of peewee. Beyond that I can't really say as I hardly know the ins and outs of MS-SQL and how it differs, what data-types it offers, etc., nor am I familiar with the python driver support.

I don't intend to support MS-SQL officially in any capacity, as I won't be able to maintain it - this should live in a 3rd-party package but if upstream API changes are required to make the integration possible I would consider those as they come up.

**Comment by Suleman-Elahi** [comment]
Here's one i created and using myself: https://github.com/Suleman-Elahi/peewee-mssql
