### ISSUE TITLE
Peewee's Datetime does not return timezone-aware datetime

### ISSUE THREAD

**Issue by thedx4** [coleifer/peewee#2959]
Peewee returns datetime object without any timezone information even when the datetime used to store it had the timezone when creating/updating the entry

For example (shortened code):

```
localtime = datetime.now(ZoneInfo('Europe/Athens'))
peewee_localtime = post.get(Post.id == some_id).created_at

print(localtime)
-> 2024-12-18 13:32:32.594483+02:00
print(peewee_localtime)
-> 2024-12-18 13:32:32.594483
```

The created_at is a MySQL datetime(6) that has the timezone stored when .save() was called. However, when retrieved from peewee the datetime created has timezone discarded.

**Comment by coleifer** [comment]
Well, yeah...you are explicitly calling `datetime.now()` with a timezone, so yes it will have zoneinfo. Peewee is just returning whatever your database driver returns. Furthermore, MySQL's datetime type does not store zoneinfo. I'd suggest reading the docs for a better sense of what MySQL offers in terms of various date/time storage: https://dev.mysql.com/doc/refman/8.4/en/datetime.html -- for MySQL the best-practice is to likely convert everything to UTC before storage, and convert back upon retrieval.

With Postgresql, in order to work with tz-aware datetimes, you can use the `playhouse.postgres_ext.DateTimeTZField` -- currently there is not a similar field for MySQL.

**Comment by thedx4** [comment]
What about MariaDB?

https://mariadb.com/kb/en/time-zones/

> Some data types are affected by the time zone settings.
>     [TIMESTAMP](https://mariadb.com/kb/en/timestamp/) - See [TIMESTAMP: Time Zones](https://mariadb.com/kb/en/timestamp/#time-zones) for information on how this data type is affected by time zones.
>     [DATETIME](https://mariadb.com/kb/en/datetime/) - See [DATETIME: Time Zones](https://mariadb.com/kb/en/datetime/#time-zones) for information on how this data type is affected by time zones.

https://mariadb.com/kb/en/timestamp/#time-zones

> Time Zones
> If a column uses the TIMESTAMP data type, then any inserted values are converted from the session's time zone to [Coordinated Universal Time (UTC)](https://mariadb.com/kb/en/coordinated-universal-time/) when stored, and converted back to the session's time zone when retrieved.

**Comment by coleifer** [comment]
MariaDB:

>then any inserted values are converted from the session's time zone to [Coordinated Universal Time (UTC)](https://mariadb.com/kb/en/coordinated-universal-time/) when stored, and converted back to the session's time zone when retrieved.

MySQL 8.x:

>MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval. (This does not occur for other types such as DATETIME.) By default, the current time zone for each connection is the server's time.

So yes, you can absolutely implement a `DateTimeTZField` that uses this storage class.

However the data returned by the database server is still a "naive" datetime. The server converts from session tz -> utc for storage, then back to session for retrieval -- but the zoneinfo is not returned, you just get a flat/naive datetime in the session timezone with the conversion already applied.
