### ISSUE TITLE
pwiz takes a very long time

### ISSUE THREAD

**Issue by digi604** [coleifer/peewee#547]
i have a db with many tables... pwiz seams to take a looong time... up to 30min to generate 1 table model

**Comment by coleifer** [comment]
Uhhh this isn't a bug really. How many tables you got? What kind of database?

**Comment by coleifer** [comment]
Also typically you'll only need to run pwiz once so even if it takes a while hopefully it's a one-time thing. pwiz takes a long time because it needs to traverse the graph of tables and introspect each one, finding col type info, constraints, indexes and foreign keys. There's no, afaik, way to speed that up. If you want to profile the code and try to find hotspots, by all means, but I think it's pretty much going to take time for large databases.
