### ISSUE TITLE
Memory usage Runs wild

### ISSUE THREAD

**Issue by prggmr** [coleifer/peewee#73]
Hello,

I believe to have found a problem with the library causing excessive memory usage when used with long running processes, the problem I encountered is when importing a very large XML file (80+GB) the memory usage would climb at a very steady rate, after exhausting all other options to what was consuming the memory I removed the peewee library and the memory consumption stopped.

I cannot say exactly where the consumption is taking place but I was only using the `select`, `update` and `insert` functions in the process, unfortunately I didn't have the time available to fully investigate what the problem is but it does exist somewhere.

During the import I was using the following snippet for extracting the data.

https://gist.github.com/2161849

The code for running the queries was identical to the following

```
if import.type is IMPORT_FULL Model.select().where(id = field['id']).exists():
    InsertQuery(Model, **fields).execute()
else:
    UpdateQuery(Model, **fields).where(id = fields['id']).execute()
```

**Comment by MRaoofnia** [comment]
i have this problem too. I am using peewee 3.11.2 , PyMySQL 0.9.3 and python 3.6
i have 20m records in my database so , to reduce ram usage, i query for 100k records each time. the problem is that records are the same and must have the same size but each query causes more ram usage than the previous one.(e.g. first query uses 100MB of ram but the 30th one uses 5GB)

**Comment by coleifer** [comment]
Without code it's impossible to help. There are many ways to profile your memory usage.

Best recommendation is to use the `.iterator()` method of query to get a "one-shot" iterator that doesn't cache rows in memory.
