### ISSUE TITLE
Fail to install peewee under WinPython

### ISSUE THREAD

**Issue by mindv0rtex** [coleifer/peewee#763]
Hi guys. I am trying to install peewee under WinPython. It comes with Cython pre-intalled, so peewee attempts to compile extensions and this is where the install fails. It complains about sqlite3.h absence and I don't know how to resolve this. Compiling sqlite3 and putting the .a file in the lib folder did not help... I asked the same question on stackoverflow and received a comment which I cannot parse...

http://stackoverflow.com/questions/33834113/fail-to-install-peewee-under-winpython

**Comment by coleifer** [comment]
Hmm, well this isn't exactly a solution, but I've released a new versoin 2.7.2 that does not build SQLite extension by default.

If you want the sqlite extension it should be built using `python setup.py build_sqlite_ext`.

I will look into checking the python version and renaming the entry-point per the stackoverflow answer. (`PyInit__sqlite_ext`).

Fuck python 3 and it's stupid ass changes.

**Comment by mindv0rtex** [comment]
FWIW, I confirm that I could successfully perform the `python setup.py build_sqlite_ext` under WinPython 2, so this indeed looks like a Python 3 issue.

**Comment by cgohlke** [comment]
Some issues with the `_sqlite_ext` extension:

1. On Python 3, the extension module fails to link. The module's init function is actually `PyInit__sqlite_ext`, not [`init_sqlite_ext`](https://github.com/coleifer/peewee/blob/master/playhouse/_sqlite_ext.pyx#L289)

2. On Python 3 for Windows, the [`sqlite3_sqliteext_init`](https://github.com/coleifer/peewee/blob/master/playhouse/_sqlite_ext.pyx#L283) function is not exported from the module. I think this is a Cython bug.

3. The [`load_extension`](https://github.com/coleifer/peewee/blob/master/playhouse/sqlite_ext.py#L711) function fails to load the `_sqlite_ext` module because the file extension of the Python extension is `.pyd`, not `.dll`. Also, on Python 3.5, the name of the Python extension is `_sqlite_ext.cp35-win_amd64.pyd` or `_sqlite_ext.cp35-win32.pyd`, not `_sqlite_ext.pyd`

**Comment by shirish93** [comment]
Hello, encountered this problem again (sorry for the duplicate issue). Would there be a fix, other than to not use peewee with Py3.X on windows?

**Comment by coleifer** [comment]
@shirish93 can you please paste the traceback?

**Comment by mahadi** [comment]
I solved the issue with my python 3.5 setup by insalling VS 2015 with the instructions of this thread:

http://stackoverflow.com/questions/33323172/vcvarsall-bat-needed-for-python-to-compile-missing-from-visual-studio-2015-v-1
