### ISSUE TITLE
pwiz password

### ISSUE THREAD

**Issue by pc10201** [coleifer/peewee#784]
when I run
```
python -m pwiz --host=127.0.0.1 --port=3306 --user=root --password=root -e mysql forex
```

result
```
Usage: pwiz.py [options] database_name

pwiz.py: error: --password option does not take a value
```

when I run
```
python -m pwiz --host=127.0.0.1 --port=3306 --user=root -P root -e mysql forex
```

result
```
Password: 
```

It need to input password again.Why?

**Comment by coleifer** [comment]
The idea is that it is bad practice to accept passwords on the command-line, since they get written to your bash history, etc.

**Comment by coleifer** [comment]
So you specify `-P`, then when prompted you enter your password in.

**Comment by churbis** [comment]
Interesting that you chose not to accept the passwords on the command line which is an explicit choice that the end user makes, however the pwiz tool itself _echos the password into the console or is piped into the file you store the models in without explicitly telling the user that their password is going to get written_.  This has led me to accidentally commit a password into a repo. You should be able to specify os.env variables to retrieve the passwords in the generated files, or else find some other paradigm to set the database on the BaseModel.

**Comment by coleifer** [comment]
> This has led me to accidentally commit a password into a repo.

Whoops, I can add a note to the docs that the password will be outputted as a connection parameter.

As far as using an environment variable, just modify the generated code to do what you want it to.

**Comment by au1985** [comment]
I am using peewee in a containerized project. There is a console program that manages the project, and I just want to run pwiz in a container where my python backend lives to get an updated schema from the database when developers change it.

All the database credentials are inside the container, and this is a standard practice. We are working with dev environment with pwiz, as expected.

Instead of simply running something like

`docker exec <CONTAINER_ID> 'python -m pwiz -H $DBHOST -p $DBPORT -u $DBUSER -p $DBPASSWORD -e postgresql $DBNAME'`

I have to ask for password or have to write an expect script just because there is no way for pwiz to accept a password non-interactively.

This is to show that enforcing users to enter password from the terminal is a flawed practice, and this is an issue we are facing with this tool, otherwise excellent. Maybe you reconsider your policy, thanks!

**Comment by coleifer** [comment]
`pwiz` is not typically something intended for use outside of interactive sessions, since it is really just a generator for skeleton code. You could, for your purposes, probably just look at the code inside pwiz's main and write your own short script.
