### ISSUE TITLE
PooledMySQLDatabase has cache or buffer?.md

### ISSUE THREAD

**Issue by tradaniel** [coleifer/peewee#814]
i create a mysql pool like this:

    database = PooledMySQLDatabase('test', max_connections=10,
                               **{'host': 'localhost', 'port': 3306,
                                  'user': 'root', 'password': ''})

    class BaseModel(Model):
        class Meta:
            database = database

    class Tb1(BaseModel):
       point_id = PrimaryKeyField()

       class Meta:
             db_table = 'tb1'

however, where i insert a record or delete a record in database  manully,  in my program, select result is not change.

    while True:
       database.connect()
       tb_list = Tb1.select()
       print(len(tb_list))
       database.close()
       import time
       time.sleep(2)
 

when i repalce  PooledMySQLDatabase to MySQLDatabase the result is normal.
In my project, I want to use multithread, so I need to create a mysql pool.

thanks a lot

**Comment by coleifer** [comment]
You don't need a pool for multi-threaded, for what it's worth. Peewee correctly handles connections and will open a connection per thread.

The issue is related to #727 and #806 . I've reverted the change in #727 so this should resolve itself. In the meantime, make sure you are using transactions! Wrap your code in `database.atomic()` blocks where you are making changes. That should help until I create a new release that has the `commit_select` change.

**Comment by coleifer** [comment]
See 6087199320a3ad8968add5d50f6c3a047767afdd
