### ISSUE TITLE
create new record can't get the database default value.

### ISSUE THREAD

**Issue by Dongin** [coleifer/peewee#909]
```
class MyModel(Model):
    create_at = DateTimeField(constraints=[SQL('DEFAULT CURRENT_TIMESTAMP')],
                              formats='%Y-%m-%d %H:%M:%S', verbose_name=‘Created time')
    other_fields = xxx

inst = MyModel.create(other_fields=xxx)
print inst.create_at is None
```
The output is **True**.

**Comment by coleifer** [comment]
Correct, because peewee is not magical, it will not magically retrieve a value that was created by the database server.

You look to be using MySQL, which AFAIK does not support INSERT ... RETURNING. So you will need to re-fetch the record or alternatively create the timestamp in Python and send it to the server.
