### ISSUE TITLE
Extra `t2` while generating query

### ISSUE THREAD

**Issue by blueset** [coleifer/peewee#983]
# Model
```python
class MsgLog(Model):
    master_msg_id = CharField(unique=True, primary_key=True)
    text = CharField()
    slave_origin_uid = CharField()
    slave_origin_display_name = CharField(null=True)
    slave_member_uid = CharField(null=True)
    slave_member_display_name = CharField(null=True)
    msg_type = CharField()
    sent_to = CharField()

    class Meta:
        database = SqliteDatabase('data.db')
```

# Query
```python
chat_id = 1
q = MsgLog.select().where(MsgLog.master_msg_id.startswith("%s." % chat_id)).order_by(MsgLog.id.desc())
print(q)
```

## Expected result
```sql
SELECT "t1"."master_msg_id", "t1"."text", "t1"."slave_origin_uid", "t1"."slave_origin_display_name", "t1"."slave_member_uid", "t1"."slave_member_display_name", "t1"."msg_type", "t1"."sent_to" FROM "msglog" AS t1 WHERE ("t1"."master_msg_id" LIKE ?) ORDER BY "t1"."id" DESC ['1.%']
```

## Returned result
```sql
SELECT "t1"."master_msg_id", "t1"."text", "t1"."slave_origin_uid", "t1"."slave_origin_display_name", "t1"."slave_member_uid", "t1"."slave_member_display_name", "t1"."msg_type", "t1"."sent_to" FROM "msglog" AS t1 WHERE ("t1"."master_msg_id" LIKE ?) ORDER BY "t2"."id" DESC ['1.%']
```

**Comment by coleifer** [comment]
q = MsgLog.select().where(MsgLog.master_msg_id.startswith("%s." % chat_id)).order_by(MsgLog.id.desc())

The problem is you're ordering by MsgLog.id but MsgLog.master_msg_id is the primary key and the model (while it has an "id" attribute), does not consider it a valid field.

To fix this, just change your "order_by()" call to order on a field that's defined on the MsgLog model. Or alternatively, you could make "master_msg_id" have "unique=True" instead of being a primary key.

**Comment by keredson** [comment]
this is a good example of why peewee should throw a meaningful exception when it's generating SQL it knows to be invalid (ie: referencing a non-existent table alias) rather than relying on the database to throw an invalid sql error.  the true cause of the error is obscured, and @blueset's conclusion that the ORM has a bug is very reasonable.

**Comment by coleifer** [comment]
I think I may make some modifications to Peewee to drop the `id` attribute if a different field is used as the foreign key.

**Comment by keredson** [comment]
@coleifer deleting other user's comments just because you don't agree with them is very uncool.

**Comment by coleifer** [comment]
I only delete yours ;)

**Comment by coleifer** [comment]
Reopening as I intend to fix.
